### ISSUE TITLE
Val cannot be reassigned

### ISSUE THREAD

**Issue by narakai** [lulululbj/AndroidUtilCodeKTX#2]
fun Context.copyToClipboard(label: String, text: String) {
    val cm = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    val clipData = ClipData.newPlainText(label, text)
    cm.primaryClip = clipData
}

最后一行报错

**Comment by narakai** [comment]
可改为 cm.setPrimaryClip(clipData)

**Comment by lulululbj** [comment]
我这边倒没有问题，setPrimaryClip() 和 .primaryClip  是用一个意思，写法不同而已。
