### ISSUE TITLE
Activity的管理

### ISSUE THREAD

**Issue by catchpig** [lulululbj/AndroidUtilCodeKTX#3]
activity的管理lifecycle这块为什么没有加进来呢?

**Comment by lulululbj** [comment]
> activity的管理lifecycle这块为什么没有加进来呢?

具体是指？

**Comment by catchpig** [comment]
activity的栈进栈出,应用的退出需要移除activity等等

**Comment by lulululbj** [comment]
> activity的栈进栈出,应用的退出需要移除activity等等
 ok，下个版本加上

**Comment by lulululbj** [comment]
@catch-pig [KtxManager](https://github.com/lulululbj/AndroidUtilCodeKTX/blob/master/ktx/src/main/java/luyao/util/ktx/core/lifecycle/KtxManager.kt)
