### ISSUE TITLE
考虑做一个 ZipFile 的扩展吗

### ISSUE THREAD

**Issue by ghost** [lulululbj/AndroidUtilCodeKTX#6]
或者做一个 zip4J 的扩展，https://github.com/srikanth-lingala/zip4j 这个 java 库非常棒，但是他的 api 不太友好，如果用 kt 封装一下就很美好了。

**Comment by lulululbj** [comment]
没有那么不友好吧， `ZipFile("xxx").addFile(...)` ，感觉不一定可以封装的更简洁了。或者你对 api 有什么想法？

**Comment by lulululbj** [comment]
@isMeiying 没有那么不友好吧， `ZipFile("xxx").addFile(...)` ，感觉不一定可以封装的更简洁了。或者你对 api 有什么想法？

**Comment by ghost** [comment]
但是它的是 java 的 api，kt 可以更简洁，例如可以这样  `File addTo File`，更符合人类的思维...然后有些地方 Zip4j 好像也不友好，不可以根据 keywords 来解压对应文件或者文件夹，而 AndroidUtilCode 的 ZipUtils 是有这个功能的。

或者我可以提 pr 吗

**Comment by lulululbj** [comment]
@isMeiying 可以，欢迎 pr

**Comment by ghost** [comment]
👌
