### ISSUE TITLE
异常捕捉

### ISSUE THREAD

**Issue by jeromekai** [lulululbj/AndroidUtilCodeKTX#9]
mException.value = e 在案例中onError方法还是接收不到

**Comment by lulululbj** [comment]
@jeromekai 例子中点击 error test 按钮没有 “Occur Error:divede by zero” 提示吗

**Comment by jeromekai** [comment]
可能描述的不够详细吧，BaseViewModel 中  val mException: MutableLiveData<Throwable> 不是也捕捉到了类似ConnectException的异常 ，为什么BaseVMAct  的onError方法没有打印呢？

**Comment by lulululbj** [comment]
@jeromekai 这应该是个有关 java 基础的问题吧。子类 MvvmActivity 覆写了父类 BaseVMActivity 的 `onError()` 方法：

```java
override fun onError(e: Throwable) {
        toast("Occur Error : ${e.message}")
}
```

当然，你加个 `super.onError(e)` ，就会调用 BaseVMActivity 的 `onError()` 方法了。

**Comment by jeromekai** [comment]
能发issues ，怎么会犯这样低级错误
